language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

env:
  - DJANGO="Django==1.6.6"

matrix:
  exclude:
    # Python 3.4 is not supported in Django before 1.7.
    - env: DJANGO="Django==1.6.9"
      python: 3.4
    # Python 2.6 support has been dropped in Django 1.7
    - python: 2.6
      env: DJANGO="Django==1.7.2"

install:
  - pip install -r requirements.txt

script: nosetests

after_success:
  - coveralls
